version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - './mongo-data:/data/db'

  zoomment-server:
    image: zoomment-server
    restart: always
    volumes:
      - ./.env.docker:/app/.env:ro
    ports:
      - 9547:9547
    depends_on:
      - mongo
